### ISSUE TITLE
分布式布置的时候，节点如何增加

### ISSUE THREAD

**Issue by forktopot** [Autumn-27/ScopeSentry-Scan#10]
<img width="594" alt="image" src="https://github.com/Autumn-27/ScopeSentry-Scan/assets/24220639/3580eefe-0b35-4762-9677-ab49559398c4">
<img width="1336" alt="image" src="https://github.com/Autumn-27/ScopeSentry-Scan/assets/24220639/1d320732-4e51-4fd0-99f4-e87fc65c95b4">
运行之后节点一直为空

**Comment by Autumn-27** [comment]
节点运行了多久？

**Comment by forktopot** [comment]
> 节点运行了多久？

十几分钟，我配置应该没问题，直接用程序运行连接不上，后面用docker起客户端是有的

**Comment by Autumn-27** [comment]
ext里边的ksundomain运行一下看看是否正常 运行成功应该会显示注册成功

**Comment by qoo7972365** [comment]
> ext里边的ksundomain运行一下看看是否正常 运行成功应该会显示注册成功

這是不是回錯帖子了

**Comment by qoo7972365** [comment]
我也是這種情況，直接用執行檔執行後卡者不能註冊上node
![image](https://github.com/Autumn-27/ScopeSentry-Scan/assets/32336596/661234bb-4903-4fc3-8f5e-848af79234b2)

**Comment by Autumn-27** [comment]
> > ext里边的ksundomain运行一下看看是否正常 运行成功应该会显示注册成功
> 
> 
> 
> 這是不是回錯帖子了

不是 程序里边调用了ksubdomain工具 scan开始会进行拉去数据库数据 会有一段时间 另外启动时会验证ksubdomain是否管用 但是ksubdomain在有些环境中会有点问题 所在可以进容器里边运行ext/ksubdomain/ksubdomain test 看是否可以执行成功 一般导致扫描端卡住就两种情况1.在拉去数据库数据，这个需要等会  2.ksubdomain获取网卡错误导致一直卡住 ，这个需要进容器看lsubdomain是否运行成功 使用上边的命令

之后我再加一些日志 还有异常处理

**Comment by laoyupg** [comment]
<img width="1001" alt="image" src="https://github.com/user-attachments/assets/c932328c-e47f-451c-8263-e23f9cae8c02">
师傅我这里也k卡住了 有解决方法吗

**Comment by laoyupg** [comment]
<img width="919" alt="image" src="https://github.com/user-attachments/assets/87064da4-b1ea-48a5-a34e-b145ea7b4cd8">
师傅我这里也卡住了 有解决办法吗

**Comment by Autumn-27** [comment]
> <img alt="image" width="919" src="https://private-user-images.githubusercontent.com/30868707/391237089-87064da4-b1ea-48a5-a34e-b145ea7b4cd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NzMwMTUsIm5iZiI6MTczMjk3MjcxNSwicGF0aCI6Ii8zMDg2ODcwNy8zOTEyMzcwODktODcwNjRkYTQtYjFlYS00OGE1LWEzNGUtYjE0NWVhN2I0Y2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDEzMTgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkOTUwNzk0MGM3NzAxMTMxYThlN2IwN2Y1ZWE5MjU2YTUzZWE1OGNlODM4OWUzZGQ0Y2Y3ZmQwMzYyZDA2MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.abkruWfOpgvxZbbRb-nVE9ybxmQHRQITsNAR-7Kb9as"> 师傅我这里也卡住了 有解决办法吗

下边显示啥
