### ISSUE TITLE
升级1.5之后 跨版本任务无法执行且无法删除

### ISSUE THREAD

**Issue by y1s3m0** [Autumn-27/ScopeSentry-Scan#19]
![image](https://github.com/user-attachments/assets/b49aa7ed-c492-4790-99dc-88fb48668746)
升级前卡了几百个任务 升级后节点就这样了

把所有运行中任务删除了 无法解决
redis 把taskinfo key删除了 无法解决

**Comment by Autumn-27** [comment]
> ![image](https://private-user-images.githubusercontent.com/34636453/392709614-b49aa7ed-c492-4790-99dc-88fb48668746.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODYxMzMsIm5iZiI6MTczMzM4NTgzMywicGF0aCI6Ii8zNDYzNjQ1My8zOTI3MDk2MTQtYjQ5YWE3ZWQtYzQ5Mi00NzkwLTk5ZGMtODhmYjQ4NjY4NzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA4MDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExYTFlM2I3NDY0Yzk3OWZiNDFlNDdhZjY0ZDNhMjBiODg0MjI0ODg3ZGM3YWE5YmMxOWY4NmFiY2FkM2UwMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WPiy28uh3XNKL50krikNDRAEy0ENSOydLl299OmbNi8) 升级前卡了几百个任务 升级后节点就这样了
> 
> 把所有运行中任务删除了 无法解决 redis 把taskinfo key删除了 无法解决

你这个发送的任务是老版本的  服务端没有更新？

**Comment by y1s3m0** [comment]
> > ![image](https://private-user-images.githubusercontent.com/34636453/392709614-b49aa7ed-c492-4790-99dc-88fb48668746.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODYxMzMsIm5iZiI6MTczMzM4NTgzMywicGF0aCI6Ii8zNDYzNjQ1My8zOTI3MDk2MTQtYjQ5YWE3ZWQtYzQ5Mi00NzkwLTk5ZGMtODhmYjQ4NjY4NzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA4MDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExYTFlM2I3NDY0Yzk3OWZiNDFlNDdhZjY0ZDNhMjBiODg0MjI0ODg3ZGM3YWE5YmMxOWY4NmFiY2FkM2UwMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WPiy28uh3XNKL50krikNDRAEy0ENSOydLl299OmbNi8) 升级前卡了几百个任务 升级后节点就这样了
> > 把所有运行中任务删除了 无法解决 redis 把taskinfo key删除了 无法解决
> 
> 你这个发送的任务是老版本的 服务端没有更新？

更新了，git pull后，删除server和scan端重新拉取docker

**Comment by Autumn-27** [comment]
首先显示版本是多少？

**Comment by y1s3m0** [comment]
server应该没问题 是可安装插件版本

**Comment by y1s3m0** [comment]
![image](https://github.com/user-attachments/assets/0a8e4db3-9698-49d5-b671-0122ff06fbc1)

**Comment by Autumn-27** [comment]
是不是 redis里边没有删干净呀？

**Comment by y1s3m0** [comment]
![image](https://github.com/user-attachments/assets/f90017f5-d26a-49f3-85cb-3bf5c32965c2)

**Comment by Autumn-27** [comment]
把NodeTask也删掉试试

**Comment by y1s3m0** [comment]
一个现象：发送stop报文后，节点会停止当前任务，然后又因为报错卡在下一个任务
![image](https://github.com/user-attachments/assets/46e63f50-a3af-4410-b461-9eb792df6a03)

**Comment by y1s3m0** [comment]
> 把NodeTask也删掉试试

好像可以 我测试下一个完整任务执行情况

**Comment by y1s3m0** [comment]
正常运行了 感谢
