### ISSUE TITLE
关于端口扫描报错

### ISSUE THREAD

**Issue by a1most** [Autumn-27/ScopeSentry-Scan#3]
你好，我字典管理里面新建了一个端口字典，名字为：all，值为1-65535，然后出现如下报错：
![image](https://github.com/Autumn-27/ScopeSentry-Scan/assets/34560797/3f540fd0-199d-46f5-815a-46289c637401)

**Comment by Autumn-27** [comment]
> 你好，我字典管理里面新建了一个端口字典，名字为：all，值为1-65535，然后出现如下报错： ![image](https://private-user-images.githubusercontent.com/34560797/339285341-3f540fd0-199d-46f5-815a-46289c637401.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNjkwMzAsIm5iZiI6MTcxODI2ODczMCwicGF0aCI6Ii8zNDU2MDc5Ny8zMzkyODUzNDEtM2Y1NDBmZDAtMTk5ZC00NmY1LTgxNWEtNDYyODljNjM3NDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA4NTIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxOTM4NDc0MWI1YzJkZTQ2MjkzMGVkY2NjMzAxYzI5NjdkNzkyOGRmM2U2NzU2YjMxYmVlZDg1ZmYyNjNkZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XHe3HxkFH2EesWxIaup4lg86cHNzdZa-QAirycSChxs)

可能是端口字典 扫描端还没有更新出来，可以等会再试试，我之后修改一下这里获取端口的逻辑

**Comment by a1most** [comment]
> > 你好，我字典管理里面新建了一个端口字典，名字为：all，值为1-65535，然后出现如下报错： ![image](https://private-user-images.githubusercontent.com/34560797/339285341-3f540fd0-199d-46f5-815a-46289c637401.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNjkwMzAsIm5iZiI6MTcxODI2ODczMCwicGF0aCI6Ii8zNDU2MDc5Ny8zMzkyODUzNDEtM2Y1NDBmZDAtMTk5ZC00NmY1LTgxNWEtNDYyODljNjM3NDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA4NTIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxOTM4NDc0MWI1YzJkZTQ2MjkzMGVkY2NjMzAxYzI5NjdkNzkyOGRmM2U2NzU2YjMxYmVlZDg1ZmYyNjNkZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XHe3HxkFH2EesWxIaup4lg86cHNzdZa-QAirycSChxs)
> 
> 可能是端口字典 扫描端还没有更新出来，可以等会再试试，我之后修改一下这里获取端口的逻辑

这一长串是不是端口的id，这里没有根据端口id获取到端口值，然后报错吗

**Comment by Autumn-27** [comment]
> > > 你好，我字典管理里面新建了一个端口字典，名字为：all，值为1-65535，然后出现如下报错： ![image](https://private-user-images.githubusercontent.com/34560797/339285341-3f540fd0-199d-46f5-815a-46289c637401.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNjkwMzAsIm5iZiI6MTcxODI2ODczMCwicGF0aCI6Ii8zNDU2MDc5Ny8zMzkyODUzNDEtM2Y1NDBmZDAtMTk5ZC00NmY1LTgxNWEtNDYyODljNjM3NDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA4NTIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxOTM4NDc0MWI1YzJkZTQ2MjkzMGVkY2NjMzAxYzI5NjdkNzkyOGRmM2U2NzU2YjMxYmVlZDg1ZmYyNjNkZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XHe3HxkFH2EesWxIaup4lg86cHNzdZa-QAirycSChxs)
> > 
> > 
> > 可能是端口字典 扫描端还没有更新出来，可以等会再试试，我之后修改一下这里获取端口的逻辑
> 
> 这一长串是不是端口的id，这里没有根据端口id获取到端口值，然后报错吗

是的
