### ISSUE TITLE
节点报错

### ISSUE THREAD

**Issue by keyuan15** [Autumn-27/ScopeSentry-Scan#5]
添加节点出现异常
`
2024-06-19 03:20:10 - [ERROR] Get RadConfig from mongodb error
2024-06-19 03:20:10 - [ERROR] UpdateNotification error notification config: mongo: no documents in result
2024-06-19 03:20:10 - [INFO] The current number of concurrent tasks: 7
2024-06-19 03:20:10 - [INFO] 创建一个新的爬虫扫描线程
2024-06-19 03:20:10 - [INFO] 创建一个新的爬虫扫描线程
2024-06-19 03:20:10 - [INFO] Register Success:node-test - version 1.3
`
![image](https://github.com/Autumn-27/ScopeSentry-Scan/assets/56430812/6adadfcf-ed6c-4dc3-8271-c1ede03a6444)

**Comment by Autumn-27** [comment]
> 添加节点出现异常 `2024-06-19 03:20:10 - [ERROR] Get RadConfig from mongodb error 2024-06-19 03:20:10 - [ERROR] UpdateNotification error notification config: mongo: no documents in result 2024-06-19 03:20:10 - [INFO] The current number of concurrent tasks: 7 2024-06-19 03:20:10 - [INFO] 创建一个新的爬虫扫描线程 2024-06-19 03:20:10 - [INFO] 创建一个新的爬虫扫描线程 2024-06-19 03:20:10 - [INFO] Register Success:node-test - version 1.3` ![image](https://private-user-images.githubusercontent.com/56430812/340805072-6adadfcf-ed6c-4dc3-8271-c1ede03a6444.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NjEwMzQsIm5iZiI6MTcxODc2MDczNCwicGF0aCI6Ii81NjQzMDgxMi8zNDA4MDUwNzItNmFkYWRmY2YtZWQ2Yy00ZGMzLTgyNzEtYzFlZGUwM2E2NDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDAxMzIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkNDdjYzZjZDMwNzQ3NDg4ZmE2MWQwNWE5M2VkMDVlMzI2NjE2OTIxNzg1OWU3ODBiNTJmNGY5MzQ3MWYxOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IZeGOIpQn6WfK2Hc_YqxS7pT4ttcw-Km1sfdeX0qLto)

看起来像是数据库没有初始化成功 可以把数据库中ScopeSentry表删除 再重启server 重新初始化

**Comment by keyuan15** [comment]
> > 添加节点出现异常 `2024-06-19 03:20:10 - [ERROR] Get RadConfig from mongodb error 2024-06-19 03:20:10 - [ERROR] UpdateNotification error notification config: mongo: no documents in result 2024-06-19 03:20:10 - [INFO] The current number of concurrent tasks: 7 2024-06-19 03:20:10 - [INFO] 创建一个新的爬虫扫描线程 2024-06-19 03:20:10 - [INFO] 创建一个新的爬虫扫描线程 2024-06-19 03:20:10 - [INFO] Register Success:node-test - version 1.3` ![image](https://private-user-images.githubusercontent.com/56430812/340805072-6adadfcf-ed6c-4dc3-8271-c1ede03a6444.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NjEwMzQsIm5iZiI6MTcxODc2MDczNCwicGF0aCI6Ii81NjQzMDgxMi8zNDA4MDUwNzItNmFkYWRmY2YtZWQ2Yy00ZGMzLTgyNzEtYzFlZGUwM2E2NDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDAxMzIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkNDdjYzZjZDMwNzQ3NDg4ZmE2MWQwNWE5M2VkMDVlMzI2NjE2OTIxNzg1OWU3ODBiNTJmNGY5MzQ3MWYxOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IZeGOIpQn6WfK2Hc_YqxS7pT4ttcw-Km1sfdeX0qLto)
> 
> 看起来像是数据库没有初始化成功 可以把数据库中ScopeSentry表删除 再重启server 重新初始化

可以了 已解决
