### ISSUE TITLE
端口问题

### ISSUE THREAD

**Issue by a1most** [Autumn-27/ScopeSentry-Scan#6]
还是端口问题，在执行包含端口扫描（使用内置的端口配置）的扫描任务时，报错如下：
![image](https://github.com/Autumn-27/ScopeSentry-Scan/assets/34560797/f8f459c4-4a54-4fbe-95a2-e9bb676d1bb3)

**Comment by Autumn-27** [comment]
> 还是端口问题，在执行包含端口扫描（使用内置的端口配置）的扫描任务时，报错如下：
> 
> ![image](https://github.com/Autumn-27/ScopeSentry-Scan/assets/34560797/f8f459c4-4a54-4fbe-95a2-e9bb676d1bb3)
> 
> 

好的 获取端口有两种方案 你的这个应该是第一种失败了 第二种成功了 我等会看看是啥情况
