### ISSUE TITLE
扫描任务问题

### ISSUE THREAD

**Issue by keyuan15** [Autumn-27/ScopeSentry-Scan#7]
问题1：
新建任务时子域名扫描不选择字典方式，但扫描过程中还会默认勾上
![image](https://github.com/Autumn-27/ScopeSentry-Scan/assets/56430812/b98030c4-591d-4993-a3ae-9b1322446771)
![image](https://github.com/Autumn-27/ScopeSentry-Scan/assets/56430812/8022e352-bcbc-47c3-83fd-689fe35c9548)

问题2：
子域名扫描，使用字典方式会扫出0.0.0.1的IP，实际测试没有这些子域名
![image](https://github.com/Autumn-27/ScopeSentry-Scan/assets/56430812/37730ce6-a139-43d4-a965-c2e80dd5f286)

问题3：
以上问题好像会导致卡在0%
![image](https://github.com/Autumn-27/ScopeSentry-Scan/assets/56430812/d339bf30-4d57-472a-a8bc-f077affa4456)

**Comment by Autumn-27** [comment]
> 问题1： 新建任务时子域名扫描不选择字典方式，但扫描过程中还会默认勾上 ![image](https://private-user-images.githubusercontent.com/56430812/340905319-b98030c4-591d-4993-a3ae-9b1322446771.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3Njk2MjcsIm5iZiI6MTcxODc2OTMyNywicGF0aCI6Ii81NjQzMDgxMi8zNDA5MDUzMTktYjk4MDMwYzQtNTkxZC00OTkzLWEzYWUtOWIxMzIyNDQ2NzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDAzNTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzYWZmNWY0OTNkYTQ2YThjYjg3YzA4MWQ2YjE0M2RjMWUzZWE4YTNiMTM5ZDBlZjc2YWY0MGNkODIyMzgzMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9m923sMcbMbUJwFsf6Pc9PPv4B091IxiTdT0rC4rZqc) ![image](https://private-user-images.githubusercontent.com/56430812/340905839-8022e352-bcbc-47c3-83fd-689fe35c9548.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3Njk2MjcsIm5iZiI6MTcxODc2OTMyNywicGF0aCI6Ii81NjQzMDgxMi8zNDA5MDU4MzktODAyMmUzNTItYmNiYy00N2MzLTgzZmQtNjg5ZmUzNWM5NTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDAzNTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjZWI4OGNlZTdhMzk5ZDBlOGNkNzk1YWUxM2MxMmY5YzVjNzg1ZDIyMTRkZTBlZjEzMGJlM2RhMDdhZTFjMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.weRmqru0pdCacWpDpQgbQpfzxhybu-B8D6rnQFlKp2c)
> 
> 问题2： 子域名扫描，使用字典方式会扫出0.0.0.1的IP，实际测试没有这些子域名 ![image](https://private-user-images.githubusercontent.com/56430812/340904793-37730ce6-a139-43d4-a965-c2e80dd5f286.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3Njk2MjcsIm5iZiI6MTcxODc2OTMyNywicGF0aCI6Ii81NjQzMDgxMi8zNDA5MDQ3OTMtMzc3MzBjZTYtYTEzOS00M2Q0LWE5NjUtYzJlODBkZDVmMjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDAzNTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhZTllNWYyMjM5ZTE4ZjIxNzZlMDE2NDViYTVlMjlkM2JlNDg2Yjk2M2I0YTg0MGQwOWY5ZDQ0MmRhMmQ5OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3KzDfoSg7cw1ADipLVbbmAVeIZBCswRGFd5wIDrjHBo)
> 
> 问题3： 以上问题好像会导致卡在0% ![image](https://private-user-images.githubusercontent.com/56430812/340905771-d339bf30-4d57-472a-a8bc-f077affa4456.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3Njk2MjcsIm5iZiI6MTcxODc2OTMyNywicGF0aCI6Ii81NjQzMDgxMi8zNDA5MDU3NzEtZDMzOWJmMzAtNGQ1Ny00NzJhLWE4YmMtZjA3N2FmZmE0NDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDAzNTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZmQxOWM4MWJiYTUzYzEzNmY4NDdmZWQ2OGYyM2U4NGQ0NGVkMjVkZTc1MmY2Nzc2OGFkODFkNGUyYjE3M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tyFlqGIiF9IhcS1y1PtWPrAmXJvypU3OrzKfQaZQ1TM)

1和2我得测一下，师傅方便加好友发下目标吗？第三个任务进度是按照目标个数计算的。由于只有一个目标所有在完成之前都是0

**Comment by keyuan15** [comment]
> > 问题1： 新建任务时子域名扫描不选择字典方式，但扫描过程中还会默认勾上 ![image](https://private-user-images.githubusercontent.com/56430812/340905319-b98030c4-591d-4993-a3ae-9b1322446771.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3Njk2MjcsIm5iZiI6MTcxODc2OTMyNywicGF0aCI6Ii81NjQzMDgxMi8zNDA5MDUzMTktYjk4MDMwYzQtNTkxZC00OTkzLWEzYWUtOWIxMzIyNDQ2NzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDAzNTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzYWZmNWY0OTNkYTQ2YThjYjg3YzA4MWQ2YjE0M2RjMWUzZWE4YTNiMTM5ZDBlZjc2YWY0MGNkODIyMzgzMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9m923sMcbMbUJwFsf6Pc9PPv4B091IxiTdT0rC4rZqc) ![image](https://private-user-images.githubusercontent.com/56430812/340905839-8022e352-bcbc-47c3-83fd-689fe35c9548.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3Njk2MjcsIm5iZiI6MTcxODc2OTMyNywicGF0aCI6Ii81NjQzMDgxMi8zNDA5MDU4MzktODAyMmUzNTItYmNiYy00N2MzLTgzZmQtNjg5ZmUzNWM5NTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDAzNTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjZWI4OGNlZTdhMzk5ZDBlOGNkNzk1YWUxM2MxMmY5YzVjNzg1ZDIyMTRkZTBlZjEzMGJlM2RhMDdhZTFjMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.weRmqru0pdCacWpDpQgbQpfzxhybu-B8D6rnQFlKp2c)
> > 问题2： 子域名扫描，使用字典方式会扫出0.0.0.1的IP，实际测试没有这些子域名 ![image](https://private-user-images.githubusercontent.com/56430812/340904793-37730ce6-a139-43d4-a965-c2e80dd5f286.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3Njk2MjcsIm5iZiI6MTcxODc2OTMyNywicGF0aCI6Ii81NjQzMDgxMi8zNDA5MDQ3OTMtMzc3MzBjZTYtYTEzOS00M2Q0LWE5NjUtYzJlODBkZDVmMjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDAzNTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhZTllNWYyMjM5ZTE4ZjIxNzZlMDE2NDViYTVlMjlkM2JlNDg2Yjk2M2I0YTg0MGQwOWY5ZDQ0MmRhMmQ5OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3KzDfoSg7cw1ADipLVbbmAVeIZBCswRGFd5wIDrjHBo)
> > 问题3： 以上问题好像会导致卡在0% ![image](https://private-user-images.githubusercontent.com/56430812/340905771-d339bf30-4d57-472a-a8bc-f077affa4456.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3Njk2MjcsIm5iZiI6MTcxODc2OTMyNywicGF0aCI6Ii81NjQzMDgxMi8zNDA5MDU3NzEtZDMzOWJmMzAtNGQ1Ny00NzJhLWE4YmMtZjA3N2FmZmE0NDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDAzNTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZmQxOWM4MWJiYTUzYzEzNmY4NDdmZWQ2OGYyM2U4NGQ0NGVkMjVkZTc1MmY2Nzc2OGFkODFkNGUyYjE3M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tyFlqGIiF9IhcS1y1PtWPrAmXJvypU3OrzKfQaZQ1TM)
> 
> 1和2我得测一下，师傅方便加好友发下目标吗？第三个任务进度是按照目标个数计算的。由于只有一个目标所有在完成之前都是0

qq加您了
